version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ./:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${SENHA}
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db